spring.application.name=supabaseS3
supabase.storage.endpoint=${SUPABASE_S3_ENDPOINT}
supabase.storage.region=${SUPABASE_S3_REGION}
supabase.storage.access-key=${SUPABASE_S3_ACCESS_KEY}
supabase.storage.secret-key=${SUPABASE_S3_SECRET_KEY}
supabase.storage.bucket=avatars

supabase.url=${SUPABASE_URL}